#! /usr/bin/env dash

restart() {
  type start && type stop || \
    error "This module can not be restarted!" fatal 1
  stop
  start
}

error() {
  >&2 echo "$1"
  [ -z "$3" ] && EXIT_CODE=1 || EXIT_CODE=2
  [ "$2" = "fatal" ] && exit "$EXIT_CODE"
}

[ -z "$DIR" ] && error "Environment variable 'DIR' is not set!" fatal 1
[ -z "$WMRC" ] && error "Environment variable 'WMRC' is not set!" fatal 1
[ -z "$MODULES" ] && error "Environment variable 'MODULES' is not set!" fatal 1

EXEC="$1"
[ -z "$EXEC" ] || ! type "$EXEC" && EXEC="start"

if type "$EXEC"; then
  "$EXEC" "$@"
else
  error "Action '$EXEC' is not defined!" fatal 1
fi