.\" Manual for wmrc.
.TH "wmrc" 1 "18 August 2023" "wmrc 2.1.0" "wmrc manual"

.SH NAME
.B wmrc
\- simple modular window manager extensions

.SH SYNOPSIS
.B wmrc
modules | call <group>/<module> <method> [args...]
.br
.B wmrc
var <variable>
.br
.B wmrc
unit <unit>
units
.br
.B wmrc
deps | check-deps
.br
.B wmrc
help | version

.SH DESCRIPTION
.P
wmrc is a shell utility for extending window manager \
capabilities using modules with dependency and error checking.

.SH COMMANDS
.HP
.B modules
.br
List of all available modules in
.I $HOME/.config/wmrc/modules
.br
Modules are organized by groups, such that every module should have path like
.I $HOME/.config/wmrc/modules/<group>/<module>

.HP
.B call
<group>/<module> [method] [args...]
.br
Call module's method with arguments
.br
When module name is provided only, calls init method without arguments

.HP
.B start | stop | restart | status
<group>/<module>
.br
Control module's background daemons

.HP
.B ps
.br
List all daemons running in the background

.HP
.B var
<variable>
.br
Print value of variable in
.I $HOME/.config/wmrc/rc.conf

.HP
.B units
.br
List of all units in
.I $HOME/.config/wmrc/rc.conf

.HP
.B unit
<unit>
.br
Sequentially runs all method calls in the unit

.HP
.B deps
.br
List of external dependencies required by all modules

.HP
.B check-deps
.br
List of missing modules and external dependencies

.SH CONFIGURATION
.SS Environment variables
%VARIABLE_NAME = <expression>
.PP
When accessing variables inside modules, they have
.B WMRC_
prefix added

.SS Configuration variables
.HP
.B %LOG_LEVEL
= <level>
.br
Logs are printed to stdout and to file
.I /tmp/wmrc@${USER}${DISPLAY}.log
.br
Available levels:
.B error, warn
(default),
.B info, debug

.HP
.B %CHECK_DEPS
= true | false (default)
.br
Check dependencies on every module call, with minor performance impact


.SS Units
[unit_name]
.br
group/module
.br
group/module::method
.br
group/module::method(arguments...) flag
.PP
Arguments shall be separated by space, like in shell scripts

.SS Unit call flags
.HP
.B wait
.br
Wait the call to complete before executing the next one

.HP
.B crit
.br
Wait the call to complete and abort further execution on failure

.SH MODULES
.SS Dependencies
External dependencies and called modules are listed for every module
as space separated values in
.B WMRC_DEPENDENCIES
global variable

.SS Libraries
Local libraries from
.I $HOME/.config/wmrc/libs
are loaded into the module according to the space separated values in
.B WMRC_LIBRARIES
global variable
.PP
Libraries may also list external dependencies and called modules,
but not other libraries
