.\" Manual for wmrc.
.TH "wmrc" 1 "18 August 2023" "wmrc 2.0.0" "wmrc manual"

.SH NAME
.B wmrc
\- simple modular window manager extensions

.SH SYNOPSIS
.B wmrc
modules | call <group>/<module> <method> [args...]
.br
.B wmrc
unit <unit>
units
.br
.B wmrc
deps | check-deps
.br
.B wmrc
help | version

.SH DESCRIPTION
.P
wmrc is a shell utility for extending window manager \
capabilities using modules with dependency and error checking.

.SH COMMANDS
.HP
.B modules
.br
List of all available modules in
.I $HOME/.config/wmrc/modules
.br
Modules are organized by groups, such that every module should have path like
.I $HOME/.config/wmrc/modules/<group>/<module>

.HP
.B call
<group>/<module> [method] [args...]
.br
Call module's method with arguments
.br
When module name is provided only, calls init method without arguments

.HP
.B unit
<unit>
.br
Sequentially runs all method calls in the unit

.HP
.B units
.br
List of all units in
.I $HOME/.config/wmrc/rc.conf

.HP
.B deps
.br
List of external dependencies required by all modules

.HP
.B check-deps
.br
List of missing external dependencies

.SH CONFIGURATION
.SS Environment variables
%VARIABLE_NAME = <expression>
.PP
Note: When accessing variables inside modules, they have
.B WMRC_
prefix added

.SS Units
[unit_name]
.br
group/module
.br
group/module::method
.br
group/module::method(arguments...)
.PP
Note: Arguments shall be separaated by space, like in shell scripts

.SH MODULES
.SS Dependencies
External dependencies are listed for every module as space separated values in
.B WMRC_DEPENDENCIES
global variable
